3350 #!/usr/bin/perl -w
3351 
3352 # Generate vectors.S, the trap/interrupt entry points.
3353 # There has to be one entry point per interrupt number
3354 # since otherwise there's no way for trap() to discover
3355 # the interrupt number.
3356 
3357 print "# generated by vectors.pl - do not edit\n";
3358 print "# handlers\n";
3359 print ".globl alltraps\n";
3360 for(my $i = 0; $i < 256; $i++){
3361     print ".globl vector$i\n";
3362     print "vector$i:\n";
3363     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
3364         print "  pushl \$0\n";
3365     }
3366     print "  pushl \$$i\n";
3367     print "  jmp alltraps\n";
3368 }
3369 
3370 print "\n# vector table\n";
3371 print ".data\n";
3372 print ".globl vectors\n";
3373 print "vectors:\n";
3374 for(my $i = 0; $i < 256; $i++){
3375     print "  .long vector$i\n";
3376 }
3377 
3378 # sample output:
3379 #   # handlers
3380 #   .globl alltraps
3381 #   .globl vector0
3382 #   vector0:
3383 #     pushl $0
3384 #     pushl $0
3385 #     jmp alltraps
3386 #   ...
3387 #
3388 #   # vector table
3389 #   .data
3390 #   .globl vectors
3391 #   vectors:
3392 #     .long vector0
3393 #     .long vector1
3394 #     .long vector2
3395 #   ...
3396 
3397 
3398 
3399 
